import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from mylinearregression import MyLinearRegression as MyLR
from sklearn.metrics import mean_squared_error

"""data = pd.read_csv("../ressources/spacecraft_data.csv")
X = np.array(data[['Age']])
Y = np.array(data[['Sell_price']])
#print("X:{}".format(X))
#print("Y:{}".format(Y))
myLR_age = MyLR(thetas = [[1000.0], [-1.0]], alpha = 2.5e-4, max_iter = 100000)
#print("predict(X):\n{}".format(myLR_age.predict_(X)))
#print(myLR_age.mse_(Y, myLR_age.predict_(X)))
myLR_age.fit_(X, Y)
#print("fit(X,Y), thetas => \n{}".format(myLR_age.thetas))
print(myLR_age.mse_(Y, myLR_age.predict_(X)))
#Output
#57636.77729...
Y_hat = myLR_age.predict_(X)
fig, ax = plt.subplots()
plt.xlabel("x1: age in years")
plt.ylabel("y: sell price (in keuros)")
plt.plot(X, Y, 'bo', label="Sell price")
plt.plot(X, Y_hat, 'o', label="Predicted sell price")
plt.title("thetas:{}\nMSE:{}".format(myLR_age.thetas, myLR_age.mse_(Y, Y_hat)))
ax.legend()

X = np.array(data[['Thrust_power']])
myLR_thrust = MyLR(thetas = [[1000.0], [-1.0]], alpha = 1.5e-4, max_iter = 200000)
myLR_thrust.fit_(X, Y)
Y_hat = myLR_thrust.predict_(X)
fig, ax = plt.subplots()
plt.xlabel("x2: thrust power (in 10km/s)")
plt.ylabel("y: sell price (in keuros)")
plt.plot(X, Y, 'go', label="Sell price")
plt.plot(X, Y_hat, 'o', label="Predicted sell price")
plt.title("thetas:{}\nMSE:{}".format(myLR_thrust.thetas, myLR_thrust.mse_(Y, Y_hat)))
ax.legend()

X = np.array(data[['Terameters']])
myLR_distance = MyLR(thetas = [[1000.0], [-1.0]], alpha = 1.5e-4, max_iter = 100000)
myLR_distance.fit_(X, Y)
Y_hat = myLR_distance.predict_(X)
fig, ax = plt.subplots()
plt.xlabel("x3: Distance that the spacecraft has travelled in terameters.")
plt.ylabel("y: sell price (in keuros)")
plt.plot(X, Y, 'o', color='purple', label="Sell price")
plt.plot(X, Y_hat, 'o', color='pink', label="Predicted sell price")
plt.title("thetas:{}\nMSE:{}".format(myLR_distance.thetas, myLR_distance.mse_(Y, Y_hat)))
ax.legend()
plt.show()"""

"""data = pd.read_csv("../ressources/spacecraft_data.csv")
X = np.array(data[['Age','Thrust_power','Terameters']])
Y = np.array(data[['Sell_price']])
my_lreg = MyLR(thetas = [[1.], [1.], [1.], [1.]], alpha = 7e-5, max_iter = 500000)
#my_lreg = MyLR(thetas = [[334.99460274], [-22.53529627], [5.85733473], [-2.58644702]], alpha = 5e-5, max_iter = 10)
#print("X:{}".format(X))
#print("Y:{}".format(Y))
my_lreg.fit_(X,Y)
#print("fit(X,Y), thetas => \n{}".format(my_lreg.thetas))
Y_hat = my_lreg.predict_(X)
#print("Y_hat:\n{}".format(Y_hat))
#print("MSE:{}".format(my_lreg.mse_(Y, Y_hat)))
fig, ax = plt.subplots()
plt.xlabel("x1: age in years")
plt.ylabel("y: sell price (in keuros)")
plt.plot(data[['Age']], Y, 'bo', label="Sell price")
plt.plot(data[['Age']], Y_hat, 'o', markersize=2, label="Predicted sell price")
plt.title("thetas:{}\nMSE:{}".format(my_lreg.thetas, my_lreg.mse_(Y, Y_hat)))
ax.legend()

fig, ax = plt.subplots()
plt.xlabel("x2: thrust power (in 10km/s)")
plt.ylabel("y: sell price (in keuros)")
plt.plot(data[['Thrust_power']], Y, 'o', color='green', label="Sell price")
plt.plot(data[['Thrust_power']], Y_hat, 'o', markersize=2, label="Predicted sell price")
plt.title("thetas:{}\nMSE:{}".format(my_lreg.thetas, my_lreg.mse_(Y, Y_hat)))
ax.legend()

fig, ax = plt.subplots()
plt.xlabel("x3: Distance that the spacecraft has travelled in terameters.")
plt.ylabel("y: sell price (in keuros)")
plt.plot(data[['Terameters']], Y, 'o', color='purple', label="Sell price")
plt.plot(data[['Terameters']], Y_hat, 'o', markersize=2, label="Predicted sell price")
plt.title("thetas:{}\nMSE:{}".format(my_lreg.thetas, my_lreg.mse_(Y, Y_hat)))
ax.legend()
plt.show()"""